import { useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { bands, concerts } from './data'
import type { Concert } from './data'
import { calendarFile, formatDate, readIds } from './lib'
import './App.css'

type Page = 'home' | 'discover' | 'bands' | 'saved'
type IconName = 'home' | 'search' | 'heart' | 'bell' | 'arrow' | 'close' | 'calendar' | 'pin'
function Icon({ name, size = 20 }: { name: IconName; size?: number }) {
  const paths: Record<IconName, ReactNode> = {
    home: <><path d="m3 10 9-7 9 7v10H3Z" /><path d="M9 20v-7h6v7" /></>,
    search: <><circle cx="10.5" cy="10.5" r="6.5" /><path d="m16 16 5 5" /></>,
    heart: <path d="M20.5 5.5a5 5 0 0 0-7 0L12 7l-1.5-1.5a5 5 0 0 0-7 7L12 21l8.5-8.5a5 5 0 0 0 0-7Z" />,
    bell: <><path d="M5 17h14l-2-3V9a5 5 0 0 0-10 0v5Z" /><path d="M10 21h4M12 2v2" /></>,
    arrow: <><path d="M4 12h15m-6-6 6 6-6 6" /></>, close: <path d="m6 6 12 12M6 18 18 6" />,
    calendar: <><rect x="3" y="5" width="18" height="16" rx="3" /><path d="M7 2v6M17 2v6M3 11h18" /></>,
    pin: <><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z" /><circle cx="12" cy="10" r="2" /></>,
  }
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]}</svg>
}
function Poster({ concert }: { concert: Concert }) {
  return <div className={`poster ${concert.palette}`} aria-hidden="true"><span className="poster-top">ENCORE PRESENTS · LIVE IN KOREA</span><div className="poster-orbit" /><strong>{concert.headline}</strong><span className="poster-bottom">{concert.date.slice(0, 10).replaceAll('-', '.')}<span>TURN IT UP ↗</span></span></div>
}
const navigation: { id: Page; label: string; icon: IconName }[] = [{ id: 'home', label: '홈', icon: 'home' }, { id: 'discover', label: '공연 둘러보기', icon: 'search' }, { id: 'bands', label: '찜한 밴드', icon: 'heart' }, { id: 'saved', label: '내 예매 일정', icon: 'calendar' }]

function App() {
  const [page, setPage] = useState<Page>('home')
  const [query, setQuery] = useState('')
  const [filter, setFilter] = useState('전체')
  const [city, setCity] = useState('전국')
  const [followed, setFollowed] = useState(() => readIds('encore.bands', ['silicagel', 'oneokrock'], bands.map(b => b.id)))
  const [saved, setSaved] = useState(() => readIds('encore.saved', [], concerts.map(c => c.id)))
  const [selected, setSelected] = useState<Concert | null>(null)
  const [toast, setToast] = useState('')
  const detailDialog = useRef<HTMLDialogElement>(null)
  const opener = useRef<HTMLElement | null>(null)
  useEffect(() => { try { localStorage.setItem('encore.bands', JSON.stringify(followed)); localStorage.setItem('encore.saved', JSON.stringify(saved)) } catch { queueMicrotask(() => setToast('브라우저 저장 공간을 사용할 수 없어 이번 방문에만 저장됩니다.')) } }, [followed, saved])
  useEffect(() => { if (!toast) return; const timer = setTimeout(() => setToast(''), 4000); return () => clearTimeout(timer) }, [toast])
  useEffect(() => { if (selected) detailDialog.current?.showModal() }, [selected])
  const navigate = (value: Page) => { setPage(value); setQuery(''); setFilter('전체'); setCity('전국') }
  const toggleBand = (id: string) => setFollowed(prev => prev.includes(id) ? prev.filter(value => value !== id) : [...prev, id])
  const toggleSaved = (id: string) => { const exists = saved.includes(id); setSaved(prev => exists ? prev.filter(value => value !== id) : [...prev, id]); setToast(exists ? '예매 일정에서 삭제했어요.' : '내 예매 일정에 저장했어요. 푸시 알림은 추후 제공됩니다.') }
  const openDetails = (concert: Concert) => { opener.current = document.activeElement as HTMLElement; setSelected(concert) }
  const closeDetails = () => { detailDialog.current?.close(); setSelected(null); opener.current?.focus() }
  const matches = (concert: Concert) => (filter === '전체' || concert.type === filter) && (city === '전국' || concert.city === city) && `${concert.title} ${concert.venue} ${concert.bandIds.map(id => bands.find(b => b.id === id)?.name).join(' ')}`.toLowerCase().includes(query.trim().toLowerCase())
  const upcoming = concerts.filter(matches).sort((a, b) => b.announcedAt.localeCompare(a.announcedAt))
  const followedConcerts = concerts.filter(c => c.bandIds.some(id => followed.includes(id))).sort((a, b) => a.ticketAt.localeCompare(b.ticketAt))
  const savedConcerts = concerts.filter(c => saved.includes(c.id)).sort((a, b) => a.ticketAt.localeCompare(b.ticketAt))
  const downloadCalendar = (concert: Concert) => { const url = URL.createObjectURL(new Blob([calendarFile(concert)], { type: 'text/calendar;charset=utf-8' })); const a = document.createElement('a'); a.href = url; a.download = `${concert.id}-sample.ics`; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000) }
  const card = (concert: Concert) => <article className="concert-card" key={concert.id}><button className="poster-button" onClick={() => openDetails(concert)} aria-label={`${concert.title} 상세 보기`}><Poster concert={concert} /></button><div className="card-content"><div className="card-tags"><span className={`tag ${concert.type === '내한' ? 'green' : ''}`}>{concert.type}</span><span className="announcement">{concert.announcedAt.slice(5).replace('-', '.')} 발표</span><button className={`save-icon ${saved.includes(concert.id) ? 'active' : ''}`} aria-label={`${concert.title} 일정 ${saved.includes(concert.id) ? '삭제' : '저장'}`} aria-pressed={saved.includes(concert.id)} onClick={() => toggleSaved(concert.id)}><Icon name="calendar" size={18} /></button></div><button className="card-title" onClick={() => openDetails(concert)}>{concert.title}</button><p>{formatDate(concert.date)}</p><span className="venue"><Icon name="pin" size={14} />{concert.venue}</span></div></article>
  const empty = (message: string) => <div className="empty"><Icon name="search" size={30} /><h3>{message}</h3><p>다른 검색어로 찾아보거나 밴드를 찜해보세요.</p><button className="outline" onClick={() => navigate('discover')}>공연 둘러보기</button></div>

  return <div className="app-shell">
    <aside className="sidebar"><a className="brand" href="#" onClick={e => { e.preventDefault(); navigate('home') }}><span className="brand-mark">e</span>encore<span className="brand-dot">.</span></a><p className="brand-caption">다음 라이브를 만나는 곳</p><nav aria-label="주 메뉴">{navigation.map(item => <button key={item.id} className={`nav-item ${page === item.id ? 'selected' : ''}`} aria-current={page === item.id ? 'page' : undefined} onClick={() => navigate(item.id)}><Icon name={item.icon} /><span>{item.label}</span>{item.id === 'bands' && <span className="count">{followed.length}</span>}</button>)}</nav><div className="sidebar-following"><span className="eyebrow">MY ARTISTS</span>{bands.filter(b => followed.includes(b.id)).map(b => <button key={b.id} onClick={() => { navigate('discover'); setQuery(b.name) }}><span className="avatar" style={{ background: b.color }}>{b.initials}</span>{b.name}<span className="online-dot" /></button>)}{!followed.length && <p>좋아하는 밴드를 찜해보세요.</p>}</div><div className="sidebar-note"><span>FOR THE LOVE OF LIVE</span><p>좋아하는 음악은<br />라이브로 완성되니까.</p><div className="sound-bars">▂ ▅ ▃ █ ▆ ▂ ▄ ▇ ▃ ▅</div></div><div className="profile"><span className="profile-avatar">♪</span><div><strong>음악을 좋아하는 당신</strong><span>로컬 프리뷰 · 로그인 없이 체험</span></div></div></aside>
    <main id="main"><header className="topbar"><span className="breadcrumb">DISCOVER YOUR NEXT LIVE</span><label className="search-box"><Icon name="search" size={18} /><input aria-label="밴드 또는 공연 검색" placeholder="밴드, 공연을 검색해보세요" value={query} onChange={e => { setQuery(e.target.value); if (page !== 'discover') setPage('discover') }} />{query && <button onClick={() => setQuery('')} aria-label="검색 지우기"><Icon name="close" size={16} /></button>}</label><button className="top-calendar" aria-label="저장한 예매 일정 보기" onClick={() => navigate('saved')}><Icon name="calendar" />{saved.length > 0 && <span>{saved.length}</span>}</button></header>
    <div className="content"><div className="demo-notice"><span className="status-dot" />PREVIEW<span>모든 공연 정보는 가상 샘플입니다. 실제 일정·예매 정보가 아닙니다.</span></div>
    {page === 'home' && <>
      <div className="page-heading"><div><span className="eyebrow">GOOD MUSIC. GREAT NIGHTS.</span><h1>다음엔, 어떤 라이브?</h1><p>기다리던 밴드부터 새로운 발견까지. 한국에서 만나요.</p></div><span className="region"><Icon name="pin" size={16} />대한민국 전체</span></div>
      <section className="hero"><div className="hero-copy"><span className="hero-label"><span className="status-dot" /> SPOTLIGHT · 내한</span><h2>Some nights<br />stay <em>forever.</em></h2><p>플레이리스트 밖에서 만나는 우리.<br />Oasis와 함께할 다음 라이브를 확인하세요.</p><button className="primary" onClick={() => openDetails(concerts[0])}>공연 자세히 보기 <Icon name="arrow" size={18} /></button><span className="hero-meta">2026.12.12 SAT <span> / </span> 고양종합운동장 · 샘플</span></div><div className="hero-art" aria-hidden="true"><div className="vinyl"><div className="vinyl-label">oasis<span>LIVE FOREVER</span></div></div><span className="art-caption">LOUDER<br />TOGETHER.</span><span className="art-star">✳</span></div></section>
      <section className="followed-section"><div className="section-heading"><h2><Icon name="heart" />내 밴드의 다음 소식 <span>{followedConcerts.length}</span></h2><button className="text-button" onClick={() => navigate('bands')}>밴드 관리 <Icon name="arrow" size={16} /></button></div>{followedConcerts.length ? <div className="updates">{followedConcerts.map(c => <button className="update" key={c.id} onClick={() => openDetails(c)}><span className={`update-symbol ${c.palette}`}><Icon name="bell" /></span><div><strong>{c.title}</strong><span>{formatDate(c.ticketAt, true)} 티켓 오픈</span></div><Icon name="arrow" size={16} /></button>)}</div> : empty('찜한 밴드의 공연 소식을 모아볼게요.')}</section>
    </>}
    {(page === 'home' || page === 'discover') && <section className="discovery"><div className="section-heading"><div><span className="eyebrow">{page === 'home' ? 'JUST ANNOUNCED' : 'FIND YOUR LIVE'}</span><h2>{page === 'home' ? '새로 발표된 공연' : '공연 둘러보기'}<span className="result-count">{upcoming.length}</span></h2>{page === 'home' && <p>찜하지 않은 밴드의 내한 소식도 놓치지 마세요.</p>}</div>{page === 'home' && <button className="text-button" onClick={() => { navigate('discover'); setFilter('내한') }}>내한 전체 보기 <Icon name="arrow" size={16} /></button>}</div><div className="filters"><div className="filter-tabs" aria-label="공연 분류">{['전체', '내한', '국내', '페스티벌'].map(value => <button key={value} className={filter === value ? 'active' : ''} aria-pressed={filter === value} onClick={() => setFilter(value)}>{value}</button>)}</div><div className="filter-right"><select aria-label="공연 지역" value={city} onChange={e => setCity(e.target.value)}>{['전국', '서울', '인천', '고양', '부산'].map(value => <option key={value}>{value}</option>)}</select><span>최근 발표순 ↓</span></div></div>{upcoming.length ? <div className="concert-grid">{upcoming.map(card)}</div> : empty('검색 결과가 없어요.')}</section>}
    {page === 'bands' && <section><div className="page-heading"><div><span className="eyebrow">YOUR MUSIC, YOUR LIVE</span><h1>좋아하는 밴드를 찜하세요.</h1><p>국내 공연도, 내한도, 페스티벌 출연도 한곳에서.</p></div><span className="region">{followed.length}팀 찜하는 중</span></div><div className="band-grid">{bands.map(b => <article className="band-card" key={b.id}><span className="band-art" style={{ background: b.color }}>{b.initials}</span><div><h2>{b.name}</h2><p>{b.country} · {b.genre}</p></div><button className={`follow-button ${followed.includes(b.id) ? 'active' : ''}`} aria-label={`${b.name} ${followed.includes(b.id) ? '찜 해제' : '찜하기'}`} aria-pressed={followed.includes(b.id)} onClick={() => toggleBand(b.id)}><Icon name="heart" size={17} />{followed.includes(b.id) ? '찜한 밴드' : '찜하기'}</button></article>)}</div><p className="local-note">찜한 밴드는 이 브라우저에 저장됩니다. 기기 간 동기화는 추후 지원합니다.</p></section>}
    {page === 'saved' && <section><div className="page-heading"><div><span className="eyebrow">MAKE IT A DATE</span><h1>내 예매 일정</h1><p>기다리는 공연의 티켓 오픈 시간을 모아보세요.</p></div></div><div className="info-banner"><Icon name="bell" />현재는 일정 저장과 캘린더 다운로드를 지원합니다. 자동 푸시 알림은 아직 제공하지 않습니다.</div>{savedConcerts.length ? <div className="schedule-list">{savedConcerts.map(c => <article key={c.id}><div className="schedule-date"><strong>{new Date(c.ticketAt).toLocaleDateString('ko-KR', { timeZone: 'Asia/Seoul', day: '2-digit' }).replace('일', '')}</strong><span>{formatDate(c.ticketAt)}</span></div><div className="schedule-info"><button className="card-title" onClick={() => openDetails(c)}>{c.title}</button><p>{formatDate(c.ticketAt, true)} 티켓 오픈</p><span>{c.venue}</span></div><button className="outline" onClick={() => downloadCalendar(c)}><Icon name="calendar" size={16} />캘린더 저장</button><button className="save-icon" onClick={() => toggleSaved(c.id)} aria-label={`${c.title} 저장한 일정 삭제`}><Icon name="close" /></button></article>)}</div> : empty('아직 저장한 예매 일정이 없어요.')}</section>}
    <footer><span className="footer-brand">encore.</span><span>당신의 다음 라이브를 위해.</span><span>© 2026 ENCORE · Prototype</span></footer></div></main>
    <nav className="mobile-nav" aria-label="모바일 메뉴">{navigation.map(item => <button key={item.id} className={page === item.id ? 'active' : ''} aria-current={page === item.id ? 'page' : undefined} onClick={() => navigate(item.id)}><Icon name={item.icon} size={21} /><span>{item.label}</span></button>)}</nav>
    <dialog ref={detailDialog} className="detail-dialog" aria-labelledby="detail-title" onCancel={e => { e.preventDefault(); closeDetails() }} onClick={e => { if (e.target === e.currentTarget) closeDetails() }} onClose={() => setSelected(null)}>{selected && <div className="detail-content"><button className="dialog-close" aria-label="공연 상세 닫기" onClick={closeDetails}><Icon name="close" /></button><Poster concert={selected} /><div className="detail-body"><span className="tag green">{selected.type} · 가상 샘플</span><h2 id="detail-title">{selected.title}</h2><p>{selected.description}</p><dl><div><dt>공연 일시</dt><dd>{formatDate(selected.date, true)}</dd></div><div><dt>공연 장소</dt><dd>{selected.city} · {selected.venue}</dd></div><div><dt>티켓 오픈</dt><dd>{formatDate(selected.ticketAt, true)}</dd></div><div><dt>샘플 가격</dt><dd>{selected.price}</dd></div></dl><div className="detail-bands">{bands.filter(b => selected.bandIds.includes(b.id)).map(b => <button className={`outline ${followed.includes(b.id) ? 'is-followed' : ''}`} key={b.id} onClick={() => toggleBand(b.id)} aria-pressed={followed.includes(b.id)}><Icon name="heart" size={16} />{b.name} {followed.includes(b.id) ? '찜 해제' : '찜하기'}</button>)}</div><button className="primary full" onClick={() => toggleSaved(selected.id)}><Icon name="calendar" size={18} />{saved.includes(selected.id) ? '예매 일정 저장 해제' : '예매 일정 저장'}</button><p className="detail-disclaimer">실제 공연 발표가 아닙니다. 예매 링크와 공식 출처는 실제 데이터 연결 후 제공됩니다.</p></div></div>}</dialog>
    {toast && <div className="toast" role="status">{toast}</div>}
  </div>
}
export default App
